-- Current job listings (from src/data/jobs.json). Safe to re-run: existing ids are skipped.
insert into job_listings (id, title, department, location, employment_type, summary, description, requirements, status, posted_date, created_date, updated_date) values
  ('6ab07c3945d515b81c9e5914', 'Technical Support Specialist', 'Technology', 'Remote', 'Contract', 'Provide tiered technical support for SaaS clients with empathy and expertise.', 'You will troubleshoot and resolve technical issues for our SaaS clients'' end users, escalating complex cases with clear documentation. We need curious, patient problem-solvers who love the puzzle.', '2+ years in technical support. Familiarity with ticketing systems. Basic SQL and API knowledge. A patient, methodical approach.', 'open', '2026-09-15', '2026-09-21T00:37:13.878000', '2026-09-21T00:37:13.878000'),
  ('6ab07c3945d515b81c9e5911', 'Customer Success Associate', 'Customer Service', 'Sydney, AU', 'Full-time', 'Be the human voice behind our clients'' brands, delivering thoughtful, resolution-focused support.', 'You will handle inbound customer inquiries across email, chat, and phone for assigned client accounts. We''re looking for empathetic problem-solvers who treat every interaction as an opportunity to build trust.', '2+ years in customer-facing roles. Exceptional written communication. Calm under pressure. A genuine desire to help people.', 'open', '2026-09-10', '2026-09-21T00:37:13.878000', '2026-09-21T00:37:13.878000'),
  ('6ab07c3945d515b81c9e5912', 'Operations Coordinator', 'Operations', 'Remote / Sydney, AU', 'Full-time', 'Orchestrate the moving parts that keep our client engagements running smoothly.', 'As Operations Coordinator, you''ll be the connective tissue between our service teams and client stakeholders. You''ll manage workflows, track SLAs, and identify process improvements that elevate our delivery.', '3+ years in operations or project coordination. Strong organizational instincts. Proficiency with modern productivity tools. A systems-thinking mindset.', 'open', '2026-09-05', '2026-09-21T00:37:13.878000', '2026-09-21T00:37:13.878000'),
  ('6ab07c3945d515b81c9e590f', 'HR Outsourcing Specialist', 'Human Resources', 'Remote / Sydney, AU', 'Full-time', 'Manage end-to-end HR operations for our enterprise clients, from onboarding to compliance.', 'As an HR Outsourcing Specialist, you will serve as the primary HR partner for multiple client accounts. You''ll oversee onboarding flows, maintain compliance documentation, and act as a trusted advisor on people matters. This role demands both operational rigor and a human touch.', '3+ years in HR operations. Strong knowledge of Australian employment law. Excellent communication skills. SHRM or AHRI certification preferred.', 'open', '2026-09-01', '2026-09-21T00:37:13.878000', '2026-09-21T00:37:13.878000'),
  ('6ab07c3945d515b81c9e5913', 'Executive Assistant', 'Administration', 'Remote', 'Full-time', 'Provide high-caliber administrative support to founders and executives at growing companies.', 'You will partner with 2-3 client executives, managing their calendars, inbox, travel, and special projects. Discretion, initiative, and impeccable judgment are essential.', '4+ years supporting C-level executives. Mastery of calendar and inbox management. Proactive by nature. Impeccable confidentiality.', 'open', '2026-08-28', '2026-09-21T00:37:13.878000', '2026-09-21T00:37:13.878000'),
  ('6ab07c3945d515b81c9e5910', 'Senior Bookkeeper', 'Finance & Bookkeeping', 'Remote', 'Full-time', 'Own the books for a portfolio of SMB clients with precision and integrity.', 'You will manage full-cycle bookkeeping for multiple clients, including AP/AR, reconciliation, and monthly reporting. We value accuracy above all — our clients trust us with their financial truth.', '5+ years bookkeeping experience. Proficiency in Xero and QuickBooks. BAS preparation knowledge. Attention to detail is non-negotiable.', 'open', '2026-08-20', '2026-09-21T00:37:13.878000', '2026-09-21T00:37:13.878000')
on conflict (id) do nothing;
